# Outputting
permalink: /subject/:title.html
paginate: 10
paginate_path: '/index:num'
timezone:      Asia/Shanghai
future: true

# Conversion # Build settings
lsi: true # 在github中是无效的
highlighter: pygments
markdown: rdiscount
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

# Serving
baseurl: /t # does not include hostname
# http://ires.qiniudn.com/
assets_url: http://s.h230.cn/my/
cdn_lib_url: http://s.h230.cn/lib/

favicon: http://s.h230.cn/my/img/favicon.ico

# 站点信息 # Site settings
title: "Zollty QB"
description: "Zollty's Question bank"
url: http://blog.zollty.com/t

# 相对于baseurl
atom_path: /atom.xml
rss_path: /rss.xml
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts" # The different types that are available to you are pages, posts, drafts or any collection in your site.
    values:
      layout: "post"

author:
    name: zollty
    email: zollty@163.com
    twitter:
    facebook:
    weibo: zollty

# comment
comments:
    duoshuo:
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: b50955356fe8e228a2474f35de44053f        # 百度统计 js 代码后的字符串

